// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniAppGIBA.Base.Database;

#nullable disable

namespace MiniAppGIBA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202000000_RemoveGroupTypeColumn")]
    partial class RemoveGroupTypeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a simplified designer file.
            // The full model snapshot is in ApplicationDbContextModelSnapshot.cs
            // This migration only removes the Type column from Groups table.
#pragma warning restore 612, 618
        }
    }
}
