// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniAppGIBA.Base.Database;

#nullable disable

namespace MiniAppGIBA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203120000_UpdateMembershipGroupForCustomFields")]
    partial class UpdateMembershipGroupForCustomFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial Designer file - the full model is in ApplicationDbContextModelSnapshot
            // This migration updates MembershipGroup to support custom fields:
            // - Adds HasCustomFieldsSubmitted column to track submission status
            // - Adds foreign key relationship from CustomFieldValues to MembershipGroups
#pragma warning restore 612, 618
        }
    }
}
